imagePullPolicy: IfNotPresent
revisionHistoryLimit: 3
gitlabUrl: https://gitlab.com
terminationGracePeriodSeconds: 3600
concurrent: 10
checkInterval: 5
logLevel: debug
logFormat: json

sessionServer:
  enabled: false

rbac:
  create: true
  clusterWideAccess: false
  podSecurityPolicy:
    enabled: false
    resourceNames:
    - gitlab-runner
  rules:
    - resources: ["pods", "secrets", "configmaps"]
      verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
    - apiGroups: [""]
      resources: ["pods/exec", "pods/attach"]
      verbs: ["create", "patch", "delete"]
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: false

service:
  enabled: false

runners:
  privileged: true
  config: |
    log_level = "debug"
    [[runners]]
      output_limit = 10000
      [runners.kubernetes]
        image = "ubuntu:22.04"
        # helper_image = "if use custom helper"
  executor: kubernetes
  secret: runner-secret

podSecurityContext:
  runAsUser: 100
  fsGroup: 65533

resources:
  limits:
    memory: 128Mi
    cpu: 100m
  requests:
    memory: 128Mi
    cpu: 100m
