controller:
  replicaCount: 2  # Количество реплик контроллера
  service:
    type: NodePort
    ports:
      http: 80
      https: 443
    nodePorts:
      http: 30080    # Порт для HTTP
      https: 30443  # Порт для HTTPS
